export enum Role {
  SUPER_ADMIN = "SUPER_ADMIN",
  ADMIN = "ADMIN",
  EMPLOYEE = "EMPLOYEE",
  DSA = "DSA",
  PARTNER = "PARTNER",
  CUSTOMER = "CUSTOMER",
}

export enum Permission {
  USER_VIEW = "USER_VIEW",
  USER_CREATE = "USER_CREATE",
  USER_UPDATE = "USER_UPDATE",
  USER_DELETE = "USER_DELETE",

  LOAN_VIEW = "LOAN_VIEW",
  LOAN_CREATE = "LOAN_CREATE",
  LOAN_UPDATE = "LOAN_UPDATE",
  LOAN_APPROVE = "LOAN_APPROVE",
  LOAN_REJECT = "LOAN_REJECT",

  KYC_VIEW = "KYC_VIEW",
  KYC_VERIFY = "KYC_VERIFY",

  COMMISSION_VIEW = "COMMISSION_VIEW",
  COMMISSION_UPDATE = "COMMISSION_UPDATE",

  REPORT_VIEW = "REPORT_VIEW",

  WALLET_VIEW = "WALLET_VIEW",
  WALLET_UPDATE = "WALLET_UPDATE",
}