export const LOAN_STATUS = {
  DRAFT: "DRAFT",
  PENDING: "PENDING",
  UNDER_REVIEW: "UNDER_REVIEW",
  DOCUMENT_PENDING: "DOCUMENT_PENDING",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
  DISBURSED: "DISBURSED",
  CLOSED: "CLOSED",
} as const;

export type LoanStatus =
  (typeof LOAN_STATUS)[keyof typeof LOAN_STATUS];

export const ACTIVE_LOAN_STATUSES = [
  LOAN_STATUS.PENDING,
  LOAN_STATUS.UNDER_REVIEW,
  LOAN_STATUS.DOCUMENT_PENDING,
];

export const SUCCESS_LOAN_STATUSES = [
  LOAN_STATUS.APPROVED,
  LOAN_STATUS.DISBURSED,
];